flaskstarter/frontend/forms.py
# flaskstarter/frontend/forms.py

# -*- coding: utf-8 -*-

import sys
from markupsafe import Markup
from flask_wtf import FlaskForm
from wtforms import (ValidationError, HiddenField, BooleanField, StringField,
                     PasswordField, SubmitField, TextAreaField, EmailField, URLField, DecimalField)
from wtforms.validators import InputRequired, Length, EqualTo, Email, DataRequired, Optional, URL

from ..utils import (NAME_LEN_MIN, NAME_LEN_MAX, PASSWORD_LEN_MIN, PASSWORD_LEN_MAX)
from ..user import Users

terms_html = Markup('<a target="blank" href="/terms">Terms of Service</a>')

class LoginForm(FlaskForm):
    next = HiddenField()
    login = EmailField(u'Email', [InputRequired()])
    password = PasswordField('Password', [InputRequired(), Length(PASSWORD_LEN_MIN, PASSWORD_LEN_MAX)])
    remember = BooleanField('Remember me')
    submit = SubmitField('Sign in')

class SignupForm(FlaskForm):
    next = HiddenField()
    name = StringField(u'Name', [InputRequired(), Length(NAME_LEN_MIN, NAME_LEN_MAX)])
    email = EmailField(u'Email', [InputRequired(), Email()])
    password = PasswordField(u'Password', [InputRequired(), Length(PASSWORD_LEN_MIN, PASSWORD_LEN_MAX)], description=u'6 or more characters.')
    agree = BooleanField(u'Agree to the ' + terms_html, [InputRequired()])
    submit = SubmitField('Sign up')

    def validate_email(self, field):
        if Users.query.filter(Users.email.ilike(field.data)).first() is not None:
            raise ValidationError(u'Cet email est déjà enregistré')

class RecoverPasswordForm(FlaskForm):
    email = EmailField(u'Your email', [Email()])
    submit = SubmitField('Send instructions')

class ChangePasswordForm(FlaskForm):
    email_activation_key = HiddenField()
    email = HiddenField()
    password = PasswordField(u'Password', [InputRequired(), Length(PASSWORD_LEN_MIN, PASSWORD_LEN_MAX)])
    password_again = PasswordField(u'Password again', [EqualTo('password', message="Le mot de passe ne correspond pas")])
    submit = SubmitField('Save')

class ContactUsForm(FlaskForm):
    nom = StringField(u'Nom', [InputRequired(), Length(max=64)])
    email = EmailField(u'Email', [InputRequired(), Email(), Length(max=64)])
    sujet = StringField(u'Sujet', [InputRequired(), Length(5, 128)])
    message = TextAreaField(u'Message', [InputRequired(), Length(10, 1024)])
    submit = SubmitField('Envoyer')

class LieuForm(FlaskForm):
    nom = StringField('Nom', validators=[DataRequired()])
    description = TextAreaField('Description', validators=[Optional()])
    ville = StringField('Ville', validators=[Optional()])
    pays = StringField('Pays', validators=[Optional()])
    image_url = URLField('URL de l\'image', validators=[Optional()])
    latitude = DecimalField('Latitude', validators=[Optional()], places=6)
    longitude = DecimalField('Longitude', validators=[Optional()], places=6)
    submit = SubmitField('Enregistrer')

flaskstarter/settings/forms.py
# flaskstarter/settings/forms.py

# -*- coding: utf-8 -*-

from flask_wtf import FlaskForm
from wtforms import ValidationError, StringField, PasswordField, SubmitField, EmailField
from wtforms.validators import InputRequired, Length, EqualTo, Email
from flask_login import current_user
from ..user import Users
from ..utils import PASSWORD_LEN_MIN, PASSWORD_LEN_MAX

class ProfileForm(FlaskForm):
    name = StringField('Name', [Length(max=50)])
    email = EmailField('Email', [InputRequired(), Email()])
    submit = SubmitField('Update')

    def validate_email(self, field):
        if Users.query.filter(Users.email.ilike(field.data), Users.id != current_user.id).first() is not None:
            raise ValidationError('This email is taken')

class PasswordForm(FlaskForm):
    password = PasswordField('Current password', [InputRequired()])
    new_password = PasswordField('New password', [InputRequired(), Length(min=PASSWORD_LEN_MIN, max=PASSWORD_LEN_MAX)])
    password_again = PasswordField('Password again', [InputRequired(), Length(min=PASSWORD_LEN_MIN, max=PASSWORD_LEN_MAX), EqualTo('new_password')])
    submit = SubmitField('Update')

    def validate_password(self, field):
        user = Users.query.filter_by(id=current_user.id).first()
        if not user or not user.check_password(field.data):
            raise ValidationError('Current password is incorrect')

flaskstarter/__init__.py
# flaskstarter/__init__.py

# Initialisation de l'application Flask

from flask import Flask
from flask_migrate import Migrate
from .extensions import db, mail, cache, login_manager, admin

# Initialisation de Flask-Migrate
migrate = Migrate()

def create_app(config_class='flaskstarter.config.DefaultConfig'):
    app = Flask(__name__)
    
    # Charger la configuration
    app.config.from_object(config_class)
    
    # Initialisation des extensions
    db.init_app(app)
    mail.init_app(app)
    cache.init_app(app)
    login_manager.init_app(app)
    admin.init_app(app)
    migrate.init_app(app, db)

    # Enregistrement des blueprints
    from .frontend.views import frontend
    from .settings.views import settings
    
    app.register_blueprint(frontend)
    app.register_blueprint(settings)

    return app

flaskstarter/app.py
# flaskstarter/app.py

# -*- coding: utf-8 -*-

from flask import Flask
from .config import DefaultConfig
from .user import Users, UsersAdmin
from .settings import settings
from .frontend import frontend, ContactUsAdmin
from .extensions import db, mail, cache, login_manager, admin
from .utils import INSTANCE_FOLDER_PATH, pretty_date

# Pour import *
__all__ = ['create_app']

DEFAULT_BLUEPRINTS = (
    frontend,
    settings,
)

def create_app(config=None, app_name=None, blueprints=None):
    # Création de l'application Flask
    if app_name is None:
        app_name = DefaultConfig.PROJECT
    if blueprints is None:
        blueprints = DEFAULT_BLUEPRINTS

    app = Flask(app_name,
                instance_path=INSTANCE_FOLDER_PATH,
                instance_relative_config=True)

    configure_app(app, config)
    configure_extensions(app)
    configure_blueprints(app, blueprints)
    configure_logging(app)
    configure_template_filters(app)
    configure_error_handlers(app)

    return app

def configure_app(app, config=None):
    app.config.from_object(DefaultConfig)
    app.config.from_pyfile('production.cfg', silent=True)
    if config:
        app.config.from_object(config)

def configure_extensions(app):
    db.init_app(app)
    mail.init_app(app)
    cache.init_app(app)
    admin.init_app(app)
    admin.add_view(ContactUsAdmin(db.session))
    admin.add_view(UsersAdmin(db.session))
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(user_id):
        return Users.query.get(int(user_id))

def configure_blueprints(app, blueprints):
    for blueprint in blueprints:
        app.register_blueprint(blueprint)

def configure_template_filters(app):
    @app.template_filter()
    def _pretty_date(value):
        return pretty_date(value)

    @app.template_filter()
    def format_date(value, format='%Y-%m-%d'):
        return value.strftime(format)

def configure_logging(app):
    if not app.debug:
        import logging
        from logging.handlers import RotatingFileHandler

        file_handler = RotatingFileHandler('error.log', maxBytes=10240, backupCount=10)
        file_handler.setLevel(logging.ERROR)
        app.logger.addHandler(file_handler)

def configure_error_handlers(app):
    @app.errorhandler(403)
    def forbidden_page(error):
        return "Oops! You don't have permission to access this page.", 403

    @app.errorhandler(404)
    def page_not_found(error):
        return "Oops! Page not found.", 404

    @app.errorhandler(500)
    def server_error_page(error):
        return "Oops! Internal server error. Please try after sometime.", 500

flaskstarter/frontend/__init__.py
# flaskstarter\frontend\__init__.py

# -*- coding: utf-8 -*-

from .models import ContactUs, ContactUsAdmin

from .views import frontend

flaskstarter/frontend/views.py
# flaskstarter/frontend/views.py

# -*- coding: utf-8 -*-

from uuid import uuid4
from itsdangerous import URLSafeSerializer
from flask import (Blueprint, render_template, current_app, request,
                   flash, url_for, redirect)
from flask_login import (login_required, login_user, current_user,
                         logout_user, login_fresh)

from ..user.models import Users
from ..user.constants import ACTIVE
from ..extensions import db
from .forms import (SignupForm, LoginForm, RecoverPasswordForm,
                    ChangePasswordForm, ContactUsForm, LieuForm)
from .models import ContactUs, Lieu
from ..emails import send_async_email

frontend = Blueprint('frontend', __name__)

@frontend.route('/', methods=['GET', 'POST'])
def index():
    if current_user.is_authenticated:
        return redirect(url_for('frontend.dashboard'))

    query = request.args.get('q', '')
    results = []

    if query:
        results = Lieu.query.filter(Lieu.nom.ilike(f'%{query}%')).all()  # Utilisation de 'nom'

    lieux = Lieu.query.limit(10).all()
    city = "une ville"

    return render_template('frontend/landing.html', _active_home=True, results=results, query=query, lieux=lieux, city=city)

@frontend.route('/lieux')
def lieux():
    lieux = Lieu.query.all()
    return render_template('frontend/lieux.html', lieux=lieux)

@frontend.route('/lieux/add', methods=['GET', 'POST'])
@login_required
def add_lieu():
    form = LieuForm()

    if form.validate_on_submit():
        lieu = Lieu(
            nom=form.nom.data,  # Assurez-vous que le modèle utilise 'nom'
            description=form.description.data,
            ville=form.ville.data,
            pays=form.pays.data,
            latitude=form.latitude.data,
            longitude=form.longitude.data,
            image_url=form.image_url.data,
            url=form.url.data  # Ajoutez ce champ s'il est requis
        )
        db.session.add(lieu)
        db.session.commit()
        flash('Lieu ajouté avec succès!', 'success')
        return redirect(url_for('frontend.lieux'))

    return render_template('frontend/add_lieu.html', form=form)

@frontend.route('/lieux/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_lieu(id):
    lieu = Lieu.query.get_or_404(id)
    form = LieuForm(obj=lieu)

    if form.validate_on_submit():
        lieu.nom = form.nom.data
        lieu.description = form.description.data
        lieu.ville = form.ville.data
        lieu.pays = form.pays.data
        lieu.latitude = form.latitude.data
        lieu.longitude = form.longitude.data
        lieu.image_url = form.image_url.data
        lieu.url = form.url.data  # Ajoutez ce champ s'il est requis
        db.session.commit()
        flash('Lieu modifié avec succès!', 'success')
        return redirect(url_for('frontend.lieux'))

    return render_template('frontend/edit_lieu.html', form=form, lieu=lieu)

@frontend.route('/lieux/delete/<int:id>', methods=['POST'])
@login_required
def delete_lieu(id):
    lieu = Lieu.query.get_or_404(id)
    db.session.delete(lieu)
    db.session.commit()
    flash('Lieu supprimé avec succès!', 'success')
    return redirect(url_for('frontend.lieux'))

@frontend.route('/contact-us', methods=['GET', 'POST'])
def contact_us():
    form = ContactUsForm()
    if form.validate_on_submit():
        _contact = ContactUs()
        form.populate_obj(_contact)
        db.session.add(_contact)
        db.session.commit()
        flash('Thanks! We\'ll get back to you shortly!', 'success')
        return redirect(url_for('frontend.contact_us'))
    return render_template('frontend/contact_us.html', form=form)

@frontend.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('frontend.index'))
    form = LoginForm(next=request.args.get('next'))
    if form.validate_on_submit():
        user = Users.query.filter_by(email=form.login.data).first()
        if user and user.check_password(form.password.data):
            if user.status_code != ACTIVE:
                flash("Please verify your email address to continue", "danger")
                return redirect(url_for('frontend.login'))
            remember = form.remember.data
            if login_user(user, remember=remember):
                flash("Logged in", 'success')
                return redirect(form.next.data or url_for('frontend.index'))
        else:
            flash('Sorry, invalid login', 'danger')
    return render_template('frontend/login.html', form=form, _active_login=True)

@frontend.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Logged out', 'success')
    return redirect(url_for('frontend.index'))

@frontend.route('/signup', methods=['GET', 'POST'])
def signup():
    if current_user.is_authenticated:
        return redirect(url_for('frontend.dashboard'))
    form = SignupForm(next=request.args.get('next'))
    if form.validate_on_submit():
        user = Users()
        user.status_code = 2
        user.account_type = 0
        form.populate_obj(user)
        db.session.add(user)
        db.session.commit()
        confirm_user_mail(form.name.data, form.email.data)
        flash('Confirmation email sent to ' + form.email.data + '. Please verify!', 'success')
        return redirect(url_for('frontend.login'))
    return render_template('frontend/signup.html', form=form, _active_signup=True)

def confirm_user_mail(name, email):
    s = URLSafeSerializer(current_app.config['SECRET_KEY'])  # Utilisez une clé secrète sécurisée
    key = s.dumps([name, email])
    subject = 'Confirm your account for ' + current_app.config['PROJECT_NAME']
    url = url_for('frontend.confirm_account', secretstring=key, _external=True)
    html = render_template('macros/_confirm_account.html', project=current_app.config['PROJECT_NAME'], url=url)
    send_async_email(subject, html, email)

@frontend.route('/confirm_account/<secretstring>', methods=['GET', 'POST'])
def confirm_account(secretstring):
    s = URLSafeSerializer(current_app.config['SECRET_KEY'])  # Utilisez une clé secrète sécurisée
    uname, uemail = s.loads(secretstring)
    user = Users.query.filter_by(email=uemail).first()
    if user:
        user.status_code = ACTIVE
        db.session.commit()
        flash('Your account was confirmed successfully!!!', 'success')
    else:
        flash('Invalid confirmation link', 'danger')
    return redirect(url_for('frontend.login'))

@frontend.route('/change_password', methods=['GET', 'POST'])
def change_password():
    if not current_user.is_authenticated or not login_fresh():
        return redirect(url_for('frontend.login'))
    form = ChangePasswordForm(email_activation_key=request.args.get("email_activation_key"), email=request.args.get("email"))
    if form.validate_on_submit():
        update_password(form.email.data, form.email_activation_key.data, form.password.data)
        flash("Your password has been changed, log in again", "success")
        return redirect(url_for("frontend.login"))
    return render_template("frontend/change_password.html", form=form)

def update_password(email, email_activation_key, password):
    user = Users.query.filter_by(email=email, email_activation_key=email_activation_key).first()
    if user:
        user.password = password
        user.email_activation_key = None
        db.session.commit()
        flash("Your password was updated", "success")
    else:
        flash("Invalid email or activation key", "danger")

@frontend.route('/dashboard')
@login_required
def dashboard():
    return render_template('frontend/dashboard.html')

@frontend.route('/profile')
@login_required
def profile():
    return render_template('frontend/profile.html')

flaskstarter/settings/__init__.py
# flaskstarter\settings\__init__.py

# -*- coding: utf-8 -*-

from .views import settings

flaskstarter/settings/views.py
# flaskstarter/settings/views.py

# -*- coding: utf-8 -*-

from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user
from ..extensions import db
from ..user import Users
from .forms import ProfileForm, PasswordForm

settings = Blueprint('settings', __name__, url_prefix='/settings')

@settings.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    user = Users.query.filter_by(email=current_user.email).first_or_404()
    form = ProfileForm(obj=user)

    if form.validate_on_submit():
        form.populate_obj(user)
        db.session.commit()
        flash('Profile Changes Saved!', 'success')

    return render_template('settings/profile.html', user=user, active="profile", form=form)

@settings.route('/password', methods=['GET', 'POST'])
@login_required
def password():
    user = Users.query.filter_by(email=current_user.email).first_or_404()
    form = PasswordForm()

    if form.validate_on_submit():
        if user.check_password(form.password.data):  # Vérifiez si l'ancien mot de passe est correct
            user.password = form.new_password.data
            db.session.commit()
            flash('Password updated.', 'success')
            return redirect(url_for('settings.profile'))
        else:
            flash('Current password is incorrect.', 'danger')

    return render_template('settings/password.html', user=user, active="password", form=form)

flaskstarter/user/__init__.py
# flaskstarter\user\__init__.py

# -*- coding: utf-8 -*-

from .models import Users, UsersAdmin
from .constants import USER_ROLE, ADMIN, USER, USER_STATUS, NEW, ACTIVE

flaskstarter/templates/frontend/add_lieu.html
<!-- flaskstarter\templates\frontend\add_lieu.html -->

{% extends 'layouts/base.html' %}

{% block body %}
<div class="container">
    <h2>Ajouter un Lieu à visiter</h2>
    <form method="post" action="{{ url_for('frontend.add_lieu') }}">
        {{ render_form(form) }}
        <button type="submit" class="btn btn-primary">Ajouter</button>
    </form>
</div>
{% endblock %}

flaskstarter/templates/frontend/add_monument.html
{% extends 'layouts/base.html' %}

{% block body %}
<div class="container">
    <h2>Ajouter un Monument</h2>
    <form method="post" action="{{ url_for('frontend.add_monument') }}">
        {{ render_form(form) }}
        <button type="submit" class="btn btn-primary">Ajouter</button>
    </form>
</div>
{% endblock %}

flaskstarter/templates/frontend/change_password.html
{% from "macros/_form.html" import render_form %}

{% set page_title = 'Change Password' %}

{% extends 'layouts/base.html' %}

{% block body %}
  <div class="container">
    <div class="row mt-5">
      <div class="col-4 offset-4">
        {{ render_form(url_for('frontend.change_password'), form)}}
      </div>
    </div>
  </div>
{% endblock %}

flaskstarter/templates/frontend/contact_us.html
{% from "macros/_form.html" import render_form %}

{% set page_title = 'Contact Us' %}

{% extends 'layouts/base.html' %}

{% block body %}
  <div class="container">
    <div class="row mt-5">
      <div class="col-4 offset-4">
        {{ render_form(url_for('frontend.contact_us'), form)}}
      </div>
    </div>
  </div>
{% endblock %}c

flaskstarter/templates/frontend/edit_lieu.html
{% extends 'layouts/base.html' %}

{% block body %}
<div class="container">
    <h2>Éditer le Lieu à Visiter</h2>
    <form method="post" action="{{ url_for('frontend.edit_lieu', id=lieu.id) }}">
        {{ render_form(form) }}
        <button type="submit" class="btn btn-primary">Enregistrer</button>
    </form>
</div>
{% endblock %}

flaskstarter/templates/frontend/edit_monument.html
{% extends 'layouts/base.html' %}

{% block body %}
<div class="container">
    <h2>Éditer le Monument</h2>
    <form method="post" action="{{ url_for('frontend.edit_monument', id=monument.id) }}">
        {{ render_form(form) }}
        <button type="submit" class="btn btn-primary">Enregistrer</button>
    </form>
</div>
{% endblock %}

flaskstarter/templates/frontend/landing.html
<!-- flaskstarter\templates\frontend\landing.html -->

{% from "macros/_form.html" import render_form %}
{% set page_title = 'Web2o - Idées de Monuments à Visiter' %}
{% extends 'layouts/base.html' %}

<!-- Leaflet CSS -->
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" />

{% block head %}
<!-- Leaflet JavaScript -->
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
{% endblock %}

{% block body %}
<script>
  document.addEventListener('DOMContentLoaded', function () {
    var map = L.map('map').setView([48.858844, 2.294351], 13); // Exemple de coordonnées pour Paris

    // Ajout d'une couche de tuiles OpenStreetMap
    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
      maxZoom: 19,
      attribution: '© OpenStreetMap contributors'
    }).addTo(map);

    // Ajouter des marqueurs pour chaque monument
    {% if monuments %}
    {% for monument in monuments %}
    // Exemple de coordonnées, ajustez selon les données de votre monument
    L.marker([{{ monument.latitude }}, {{ monument.longitude }}]).addTo(map)
    .bindPopup('<b>{{ monument.name }}</b><br>{{ monument.description }}');
  {% endfor %}
  {% endif %}
  });
</script>

<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2 text-center">
      <h2 class="mt-5">Bienvenue sur Web2o</h2>
      <p class="lead">Vous aimez voyager et cherchez des monuments à visiter ? Remplissez le formulaire ci-dessous pour
        découvrir des monuments partout dans le monde.</p>
    </div>
    <div class="col-lg-8 offset-lg-2 text-center">
      <!-- Formulaire de recherche -->
      <form method="get" action="{{ url_for('frontend.index') }}">
        <input type="text" name="q" placeholder="Search for monuments..." value="{{ query }}">
        <button type="submit">Search</button>
      </form>

      <!-- Résultats de la recherche -->
      {% if query %}
      <h2>Search Results for "{{ query }}"</h2>
      {% if results %}
      <ul>
        {% for monument in results %}
        <li>{{ monument.name }} - {{ monument.description }}</li>
        {% endfor %}
      </ul>
      {% else %}
      <p>No results found.</p>
      {% endif %}
      {% endif %}

      <!-- Autres contenus de la page d'accueil -->

    </div>
    <div class="col-lg-8 offset-lg-2 text-center mt-5">
      {% if monuments %}
      <h3>Monuments à visiter près de {{ city }} :</h3>
      <table class="table table-bordered mt-3">
        <thead>
          <tr>
            <th>Nom</th>
            <th>Localisation</th>
            <th>Description</th>
          </tr>
        </thead>
        <tbody>
          {% for monument in monuments %}
          <tr>
            <td>{{ monument.name }}</td>
            <td>{{ monument.location }}</td>
            <td>{{ monument.description }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      {% else %}
      <p class="text-muted">Veuillez entrer une ville pour voir les monuments à visiter.</p>
      {% endif %}
    </div>
    <div class="col-lg-8 offset-lg-2 text-center mt-5">
      <!-- Div pour la carte OpenStreetMap -->
      <div id="map" style="height: 400px;"></div>
    </div>
  </div>
</div>

<footer class="footer mt-5">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <h5>À propos</h5>
        <p>Description du site et de son objectif...</p>
      </div>
      <div class="col-md-4">
        <h5>Crédits</h5>
        <p>Informations sur les contributions, sources, etc...</p>
      </div>
      <div class="col-md-4">
        <h5>Contact</h5>
        <p>Informations de contact ou formulaire de contact...</p>
      </div>
    </div>
  </div>
</footer>

{% endblock %}

flaskstarter/templates/frontend/lieux.html
{% extends 'layouts/base.html' %}

{% block body %}
<div class="container">
    <h2>Liste des Lieux à visiter</h2>
    <a href="{{ url_for('frontend.add_lieu') }}" class="btn btn-primary">Ajouter un Lieu à visiter</a>
    <table class="table mt-3">
        <thead>
            <tr>
                <th>Nom</th>
                <th>Description</th>
                <th>Ville</th>
                <th>Pays</th>
                <th>Latitude</th>
                <th>Longitude</th>
                <th>Image</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for lieu in lieux %}
            <tr>
                <td>{{ lieu.name }}</td>
                <td>{{ lieu.description }}</td>
                <td>{{ lieu.location }}</td>
                <td><img src="{{ lieu.image_url }}" alt="Image" style="width: 100px;"></td>
                <td>
                    <a href="{{ url_for('frontend.edit_lieu', id=lieu.id) }}" class="btn btn-warning">Éditer</a>
                    <form action="{{ url_for('frontend.delete_lieu', id=lieu.id) }}" method="post"
                        style="display:inline;">
                        <button type="submit" class="btn btn-danger">Supprimer</button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

flaskstarter/templates/frontend/login.html
<!-- flaskstarter\templates\frontend\login.html -->

{% from "macros/_form.html" import render_form %}

{% set page_title = 'Login' %}

{% extends 'layouts/base.html' %}

{% block body %}
<div class="container">
  <div class="row mt-5">
    <div class="col-4 offset-4">
      {{ render_form(url_for('frontend.login'), form)}}
      <a href="{{url_for('frontend.reset_password')}}" class="auth-link">Forgot Password?</a>
    </div>
  </div>
</div>
{% endblock %}

flaskstarter/templates/frontend/reset_password.html
{% from "macros/_form.html" import render_form %}

{% set page_title = 'Reset Password' %}

{% extends 'layouts/base.html' %}

{% block body %}
  <div class="container">
    <div class="row mt-5">
      <div class="col-lg-4 offset-4">
        {{ render_form(url_for('frontend.reset_password'), form)}}
      </div>
    </div>
  </div>
{% endblock %}

flaskstarter/templates/frontend/signup.html
{% from "macros/_form.html" import render_form %}

{% set page_title = 'Sign Up' %}

{% extends 'layouts/base.html' %}

{% block body %}
  <div class="container">
    <div class="row mt-5">
      <div class="col-lg-4 offset-4">
        {{ render_form(url_for('frontend.signup'), form)}}
      </div>
    </div>
  </div>
{% endblock %}